# Generated by Django 5.0.6 on 2024-06-20 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_category_id_permission_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_perm', to='posts.post'),
        ),
    ]
