# Generated by Django 5.0.6 on 2024-06-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_permission_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_set', to='posts.post'),
        ),
    ]
